### ISSUE TITLE
i have an issue i cant run the drkgen.py file

### ISSUE THREAD

**Issue by nitay100** [DrkTheDon/drkgen#1]
I can't run the file because it's not found pyfade here:Traceback (most recent call last):
  File "C:\Users\****\Desktop\drkgen-main\drkgen.py", line 14, in <module>
    import pyfade
ModuleNotFoundError: No module named 'pyfade'

[process exited with code 1]

**Comment by DaRkSurface** [comment]
Sorry for the long time, I'm not that active on github, I've included a "requirements.txt" file in the repository that has all the installations on the modules used, you seem not to have "pyfade" installed, to install all the required modules do, ```pip3 install -r requirements.txt" or "pip install -r requirements.txt" Hope this helps!

**Comment by icuyicu89** [comment]
' instead of 'python3'
python is already the newest version (3.11.1-2).
The following packages were automatically installed and are no longer required:
  attr libcap
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
~/drkgen $ apt-get update && upgrade
Hit:1 https://mirrors.sahilister.in/termux/termux-main stable InRelease
Hit:2 https://mirrors.sahilister.in/termux/termux-root root InRelease
Hit:3 https://mirrors.sahilister.in/termux/termux-x11 x11 InRelease
Reading package lists... Done
No command upgrade found, did you mean:
 Command topgrade in package topgrade
~/drkgen $ apt-get update
Hit:1 https://mirrors.sahilister.in/termux/termux-main stable InRelease
Hit:2 https://mirrors.sahilister.in/termux/termux-root root InRelease
Hit:3 https://mirrors.sahilister.in/termux/termux-x11 x11 InRelease
Reading package lists... Done
~/drkgen $ apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  attr libcap
Use 'apt autoremove' to remove them.
The following packages have been kept back:
  gst-plugins-base
The following packages will be upgraded:
  command-not-found libc++ libcairo
  libcap libde265 libjpeg-turbo
  libpaper libx11 micro ndk-sysroot
  openal-soft openssh
  openssh-sftp-server php proot
  xkeyboard-config
16 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 18.4 MB of archives.
After this operation, 516 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://mirrors.sahilister.in/termux/termux-main stable/main aarch64 libc++ aarch64 25c [221 kB]
Get:2 https://mirrors.sahilister.in/termux/termux-main stable/main aarch64 command-not-found aarch64 2.1.0-9 [218 kB]
Get:3 https://mirrors.sahilister.in/termux/termux-main stable/main aarch64 libx11 aarch64 1.8.4 [1934 kB]
Get:4 https://mirrors.sahilister.in/termux/termux-main stable/main aarch64 libcairo aarch64 1.17.8 [472 kB]
Get:5 https://mirrors.sahilister.in/termux/termux-main stable/main aarch64 libcap aarch64 2.67 [73.1 kB]
Get:6 https://mirrors.sahilister.in/termux/termux-main stable/main aarch64 libde265 aarch64 1.0.11 [147 kB]
Get:7 https://mirrors.sahilister.in/termux/termux-main stable/main aarch64 libjpeg-turbo aarch64 2.1.5 [285 kB]
Get:8 https://mirrors.sahilister.in/termux/termux-main stable/main aarch64 libpaper aarch64 2.0.6 [24.0 kB]
Get:9 https://mirrors.sahilister.in/termux/termux-main stable/main aarch64 micro aarch64 2.0.11-2 [3174 kB]
Get:10 https://mirrors.sahilister.in/termux/termux-main stable/main aarch64 ndk-sysroot aarch64 25c [1391 kB]
Get:11 https://mirrors.sahilister.in/termux/termux-main stable/main aarch64 openal-soft aarch64 1.23.0 [439 kB]
Get:12 https://mirrors.sahilister.in/termux/termux-main stable/main aarch64 openssh-sftp-server aarch64 9.2p1 [45.2 kB]
Get:13 https://mirrors.sahilister.in/termux/termux-main stable/main aarch64 openssh aarch64 9.2p1 [764 kB]
Get:14 https://mirrors.sahilister.in/termux/termux-main stable/main aarch64 php aarch64 8.2.2 [8762 kB]
Get:15 https://mirrors.sahilister.in/termux/termux-main stable/main aarch64 proot aarch64 5.1.107-55 [81.6 kB]
Get:16 https://mirrors.sahilister.in/termux/termux-x11 x11/main aarch64 xkeyboard-config all 2.38 [357 kB]
Fetched 18.4 MB in 6s (3162 kB/s)
(Reading database ... 40553 files and directories currently installed.)
Preparing to unpack .../libc++_25c_aarch64.deb ...
Unpacking libc++ (25c) over (25b) ...
Setting up libc++ (25c) ...
(Reading database ... 40553 files and directories currently installed.)
Preparing to unpack .../00-command-not-found_2.1.0-9_aarch64.deb ...
Unpacking command-not-found (2.1.0-9) over (2.1.0-8) ...
Preparing to unpack .../01-libx11_1.8.4_aarch64.deb ...
Unpacking libx11 (1.8.4) over (1.8.3-2) ...
Preparing to unpack .../02-libcairo_1.17.8_aarch64.deb ...
Unpacking libcairo (1.17.8) over (1.17.6) ...
Preparing to unpack .../03-libcap_2.67_aarch64.deb ...
Unpacking libcap (2.67) over (2.66) ...
Preparing to unpack .../04-libde265_1.0.11_aarch64.deb ...
Unpacking libde265 (1.0.11) over (1.0.10) ...
Preparing to unpack .../05-libjpeg-turbo_2.1.5_aarch64.deb ...
Unpacking libjpeg-turbo (2.1.5) over (2.1.4) ...
Preparing to unpack .../06-libpaper_2.0.6_aarch64.deb ...
Unpacking libpaper (2.0.6) over (2.0.5) ...
Preparing to unpack .../07-micro_2.0.11-2_aarch64.deb ...
Unpacking micro (2.0.11-2) over (2.0.11-1) ...
Preparing to unpack .../08-ndk-sysroot_25c_aarch64.deb ...
Unpacking ndk-sysroot (25c) over (25b-3) ...
Preparing to unpack .../09-openal-soft_1.23.0_aarch64.deb ...
Unpacking openal-soft (1.23.0) over (1.22.2) ...
Preparing to unpack .../10-openssh-sftp-server_9.2p1_aarch64.deb ...
Unpacking openssh-sftp-server (9.2p1) over (9.1p1) ...
Preparing to unpack .../11-openssh_9.2p1_aarch64.deb ...
Unpacking openssh (9.2p1) over (9.1p1) ...
Preparing to unpack .../12-php_8.2.2_aarch64.deb ...
Unpacking php (8.2.2) over (8.2.1) ...
Preparing to unpack .../13-proot_5.1.107-55_aarch64.deb ...
Unpacking proot (5.1.107-55) over (5.1.107-54) ...
Preparing to unpack .../14-xkeyboard-config_2.38_all.deb ...
Unpacking xkeyboard-config (2.38) over (2.37) ...
Setting up micro (2.0.11-2) ...
Setting up openssh-sftp-server (9.2p1) ...
Setting up php (8.2.2) ...
Setting up proot (5.1.107-55) ...
Setting up openssh (9.2p1) ...
Setting up ndk-sysroot (25c) ...
Setting up libcap (2.67) ...
Setting up libde265 (1.0.11) ...
Setting up openal-soft (1.23.0) ...
Setting up libx11 (1.8.4) ...
Setting up xkeyboard-config (2.38) ...
Setting up libpaper (2.0.6) ...
Setting up command-not-found (2.1.0-9) ...
Setting up libjpeg-turbo (2.1.5) ...
Setting up libcairo (1.17.8) ...
~/drkgen $ ls
LICENSE    assets     generated
README.md  drkgen.py  requirements.txt
~/drkgen $ python3 drkgen.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/drkgen/drkgen.py", line 14, in <module>
    import pyfade
ModuleNotFoundError: No module named 'pyfade'
~/drkgen $ pip install -r requirements.txt
Collecting colorama==0.4.3
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting discord.py==1.7.3
  Using cached discord.py-1.7.3-py3-none-any.whl (786 kB)
ERROR: Could not find a version that satisfies the requirement pyfade==3.1 (from versions: none)
ERROR: No matching distribution found for pyfade==3.1
~/drkgen $ pip3 install -r requirements.txt
Collecting colorama==0.4.3
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting discord.py==1.7.3
  Using cached discord.py-1.7.3-py3-none-any.whl (786 kB)
ERROR: Could not find a version that satisfies the requirement pyfade==3.1 (from versions: none)
ERROR: No matching distribution found for pyfade==3.1
~/drkgen $ pip install -r requirements.txt
Collecting colorama==0.4.3
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting discord.py==1.7.3
  Using cached discord.py-1.7.3-py3-none-any.whl (786 kB)
ERROR: Could not find a version that satisfies the requirement pyfade==3.1 (from versions: none)
ERROR: No matching distribution found for pyfade==3.1

**Comment by icuyicu89** [comment]
Can't start drkgen.py

**Comment by Xeonthefirst** [comment]
> Can't start drkgen.py

yes this is because system cant find pyfade same error for me... dont know how to fix

**Comment by ColdCawfee** [comment]
i found the fix for that, download and extract this zip, then run "pip install pyfade-3.1-py3-none-any.whl", installs it perfectly for me.
[pyfade-3.1-py3-none-any.zip](https://github.com/DrkTheDon/drkgen/files/10951667/pyfade-3.1-py3-none-any.zip)

**Comment by strus-uso** [comment]
I'm using termux btw
~/drkgen $ bash drkgen.py
drkgen.py: line 12: import: command not found
drkgen.py: line 13: import: command not found
drkgen.py: line 14: import: command not found
drkgen.py: line 15: import: command not found
drkgen.py: line 16: from: command not found
drkgen.py: line 17: import: command not found
drkgen.py: line 18: import: command not found
drkgen.py: line 19: import: command not found
drkgen.py: line 20: from: command not found
drkgen.py: line 21: import: command not found
drkgen.py: line 22: import: command not found
drkgen.py: line 25: syntax error near unexpected token `('
drkgen.py: line 25: `now = datetime.now()'

**Comment by DrkTheDon** [comment]
guys dont use this version of DrkGEN, it will not work as it is outdated, new one can be found here.
https://discord.gg/xSRmBPavqj
